[package]
name = "tetable"
version = "0.1.0"
edition = "2024"

[dependencies]
alum = { version = "0.6", git = "https://github.com/ranjeethmahankali/alum/", branch = "tetable-misc-improvements" }
three-d = { version = "0.18", features = ["egui-gui"] }
rfd = "0.15"